### ISSUE TITLE
loopback

### ISSUE THREAD

**Issue by sirkitree** [ben-bradley/generator-ham#1]
Hi! Thanks for such an interesting generator. It's pretty much exactly what we're looking for for a couple upcoming projects so we're giving it a try.

I'm sure we'll have more questions, but the first one is about the loopback route.

Upon generating a new server and plugin, the plugin html has `<script src='/loopback/{{appFile}}'></script>` which does not resolve to anything. I gather the intention is to include the app.js file alongside of the index.html, but it's not working.

It seems like the ui.route with the path '/{p*}' should maybe be picking this up?

**Comment by ben-bradley** [comment]
Hi Jerad,

  The loopback module was a basic plugin that I wrote to demo the framework.  The intent for it was to simply turn around the request and return data elements like header, path, querystring, etc.  It looks like that slipped through on the plugin template.

  The `{{appFile}}` template variable is populated by Handlebars when the server is started and it needs to point at the `app.js` file which can be found at `GET /{pluginName}/app.js`.  I'm updating the template so it should be able to do that now in 0.0.5.
